### ISSUE TITLE
readme error: test.py does not support --nominal flag

### ISSUE THREAD

**Issue by luigiberducci** [MIT-REALM/gcbf-pytorch#3]
Hi, thanks for your work. 
I wanted to report an error in the readme, which suggest to run the nominal controller with the command
```
python test.py --env <env> -n <number-of-agents> --nominal --epi <number-of-episodes>
```

However, the --nominal flag is not argument of test.py

**Comment by syzhang092218-source** [comment]
Thanks for bringing it up! We have fixed the README.
